In [1]:
import tensorflow as tf

In [3]:
print(f'wersja tensorflow: {tf.__version__}')

wersja tensorflow: 2.10.1


In [6]:
#pobieranie danych mnist
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

Budowa modelu **uczenia maszynowego**

In [7]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [9]:
#wektor wyników -> logit (log-odds)
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.11654705, 0.65460557, 0.30204442, 0.20586699, -0.01288179,
 -0.68803364, 0.2513727 , 0.43532872, -0.21562214, -0.25170892]],
 dtype=float32)

In [10]:
tf.nn.softmax(predictions).numpy()

array([[0.09741943, 0.16684817, 0.11727518, 0.10652138, 0.08559243,
 0.04357332, 0.11148069, 0.13399565, 0.06988539, 0.06740841]],
 dtype=float32)

In [11]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [12]:
loss_fn(y_train[:1],predictions).numpy()

3.1333103

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [15]:
#trening i ocena modelu
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2924 - accuracy: 0.9157
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1430 - accuracy: 0.9570
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1080 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0875 - accuracy: 0.9730
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0750 - accuracy: 0.9764


In [16]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0740 - accuracy: 0.9773 - 593ms/epoch - 2ms/step


[0.07403776049613953, 0.9772999882698059]

In [17]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [18]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.7318314e-08, 1.6322314e-09, 3.3118636e-06, 3.4884876e-04,
        7.8871076e-12, 4.0727468e-07, 9.5219365e-14, 9.9964583e-01,
        1.7052997e-07, 1.4589172e-06],
       [1.7195389e-07, 6.9297486e-05, 9.9992251e-01, 6.2201420e-06,
        1.0078232e-14, 1.2781861e-06, 2.6153108e-07, 6.4523473e-14,
        3.9194882e-07, 9.9590789e-13],
       [1.8459754e-07, 9.9772042e-01, 1.5023176e-04, 5.4461862e-06,
        8.1847786e-05, 9.6587482e-06, 1.1911008e-04, 4.4500188e-04,
        1.4586682e-03, 9.4634879e-06],
       [9.9979836e-01, 1.2764724e-09, 8.0838363e-05, 1.0924700e-06,
        7.4355182e-07, 4.3054929e-06, 5.4262426e-05, 2.7017924e-05,
        1.1808205e-06, 3.2184671e-05],
       [3.1962525e-06, 9.8356900e-10, 6.8719346e-06, 2.6637530e-09,
        9.9965715e-01, 5.8183821e-07, 1.1073691e-06, 2.3424849e-05,
        5.5926029e-07, 3.0715816e-04]], dtype=float32)>